general:
  kafka-topic: transactions-topic
  kafka-bootstrap-servers: localhost:9092

spring:
  datasource:
    url: jdbc:h2:file:./mydb;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update  # Use 'update' to keep the schema in sync with the entities
    show-sql: true
  h2:
    console:
      enabled: true